apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-core-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-core
  template:
    metadata:
      labels:
        app: graphql-core
    spec:
      imagePullSecrets:
        - name: ensemblweb-pull-secret 
      containers:
        - name: graphql-core
          image: DOCKER_IMAGE
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: graphql-core-configmap
            - secretRef:
                name: mongo-config
          command: ["uvicorn"]
          args: [
            "--host",
            "0.0.0.0",
            "--port",
            "8000",
            "graphql_service.server:APP"
          ]
