apiVersion: v1
kind: Secret
metadata:
  name: mongo-config
type: Opaque
# the data bit will look like this for multiple collections
data:
  # Base64 encoded values
  mongo_host: MONGO_HOST_NAME(S)_SEPARATEDBY_COMMA
  mongo_port: MONGO_PORT
  mongo_user: MONGO_DB_USER
  mongo_password: MONGO_DB_PASS
  mongo_default_db: MONGO_DEFAULT_DB
  grpc_host: GRPC_HOST
  grpc_port: GRPC_PORT
  WORKERS: "4"
  redis_host: REDIS_HOST
  redis_port: REDIS_PORT
  redis_expiry_seconds: "6600" # 1 hour
