apiVersion: v1
kind: Secret
metadata:
  name: mongo-config
type: Opaque
data:
  # Base64 encoded values
  mongo_host: MONGO_HOST_NAME(S)_SEPARATEDBY_COMMA
  mongo_port: MONGO_PORT
  mongo_db: MONGO_DATABASE_NAME
  mongo_user: MONGO_DB_USER
  mongo_password: MONGO_DB_PASS
  mongo_default_collection: MONGO_DB_COLLECTION
  mongo_lookup_service_collection: MONGO_LOOKUP_COLLECTION
  grpc_host: GRPC_HOST
  grpc_port: GRPC_PORT
