apiVersion: v1
kind: Secret
metadata:
  name: mongo-config
type: Opaque
data:
  # Base64 encoded values
  host: HOST_NAME(S)_SEPARATEDBY_COMMA
  port: PORT
  database: DATABASE_NAME
  username: DB_USER
  password: DB_PASS
  collection: DB_COLLECTION
