apiVersion: v1
kind: Service
metadata:
  name: graphql-core-svc
  labels:
    app: graphql-core-svc
spec:
  selector:
    app: graphql-core
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000