# Stages for the CI/CD job
stages:
  - test
  - build
  - deploy

# Default variables available across all the jobs
variables:
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  # Specifying DOCKER_HOST fixes "error during connect: Post http://docker:2375/v1.40/auth: dial tcp: lookup docker on 192.168.65.5:53: no such host"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

# Template to build docker image
.build:
  stage: build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker
  services:
    - ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

  script:
    - docker build -t ${DOCKER_IMAGE} --no-cache -f k8s/Dockerfile .
    - docker push ${DOCKER_IMAGE}
    # remove local image from shared runner
    - docker rmi ${DOCKER_IMAGE}
    - docker logout $CI_REGISTRY

# Template to deploy application to k8s cluster
.deploy:
  stage: deploy
  # TODO consider pointing to the Dockerhub/dependency proxy version of this
  # https://gitlab.ebi.ac.uk/ensembl-apps/thr_k8s/-/blob/fix/docker_limit/.gitlab-ci.yml#L59
  image: dockerhub.ebi.ac.uk/ensembl-apps/ensembl-thoas/deploy-tools:latest

  script:
    - sed -i "s#<DOCKER_IMAGE>#${DOCKER_IMAGE}#g" k8s/web-prod/thoas_deployment.yaml
    - kubectl apply -f k8s/web-prod/thoas_deployment.yaml

# Run a suite of unit and integration tests
test:
  image: dockerhub.ebi.ac.uk/ensembl-web/software/python:3.7.9-slim-stretch
  stage: test
  before_script:
    - pip3 install -r requirements-dev.txt
    - export META_CLASSIFIER_PATH=$PWD/docs/metadata_classifiers/
  script:
    - pylint graphql_service --fail-under=9
    - mypy graphql_service
    - pytest

# Build docker image for k8s-deploy branch
build:
  extends: .build
  only:
    - docker-rate-limiting

# deploy application to k8s cluster for k8s-deploy branch
deploy:
  extends: .deploy
  environment:
    name: thoas-graphql
  only:
    - docker-rate-limiting
