apiVersion: v1
# host refers to a Service that routes traffic outside k8s
data:
  mongo.conf: |
    [MONGO DB]
    user = <USERNAME>
    password = <PASS>
    host = <MONGO_HOST/SVC>
    port = <MONGO_PORT>
    db = <DATABASE_NAME>
    collection = <COLLECTION>
kind: ConfigMap
metadata:
  name: thoas-configmap
