apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: thoas-backdoor-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: thoas-server-svc
            servicePort: 31497
