# Apps is using a NodePort Service instead of ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: graphql-core-svc
  namespace: ensembl-apps
  labels:
    app: graphql-core-svc
spec:
  selector:
    app: graphql-core
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30152
