apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ensembl-apps

resources:
- ../../base
- apps-service.yaml

patchesStrategicMerge:
  # Base includes ingress, but apps must stay NodePort-only.
  - ingress-delete.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: graphql-core-deployment
    path: patch.yaml
