apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: graphql-core-deployment
    path: patch.yaml
