FROM python:3.7.9-slim-stretch as build
# Contains relevant basics for Python, like GCC and similar by default
LABEL maintainer="kamal@ebi.ac.uk"

COPY . /app

RUN pip3 install -r /app/requirements-api.txt -e /app/

ENV PYTHONPATH=\$PYTHONPATH:/app

EXPOSE 8000

WORKDIR /app

CMD uvicorn --workers 2 --env /app/k8s/k8s-mongo.conf --host=0.0.0.0 graphql_service.server:APP
